### ISSUE TITLE
Add CI job for Windows.

### ISSUE THREAD

**Issue by andreabonvini** [andreabonvini/pointprocess#13]

**Comment by mohitsaxenaknoldus** [comment]
Do you want to be able to build this on Windows on CI?

**Comment by andreabonvini** [comment]
Yup!

**Comment by mohitsaxenaknoldus** [comment]
I can't find how to build this project in the README. I guess running `build.sh` is all there is?

**Comment by andreabonvini** [comment]
Hi @mohitsaxenaknoldus , following the instructions specified in the [documentation](https://pointprocess.readthedocs.io/en/latest/) should be enough. `build.sh` has been added by @nikkaramessinis and I think it's just the bash script used to build the project in order to produce coverage info. (see `pointprocess/.github/workflows/main.yml` at line `43`.

**Comment by mohitsaxenaknoldus** [comment]
Ok! I'll try it, you can assign this to me.

**Comment by andreabonvini** [comment]
Nice 👍 I guess that you should just find a way to automatically install the dependencies, thanks!

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/andreabonvini/pointprocess/pull/18
